# Generated by Django 3.2 on 2023-07-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название произвидения')),
                ('year', models.IntegerField(verbose_name='Год создания')),
                ('rating', models.IntegerField(null=True, verbose_name='Рейтинг')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Произведение',
            },
        ),
    ]
