# Generated by Django 3.2 on 2023-07-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название жанра')),
                ('slug', models.SlugField(unique=True, verbose_name='строка идентификатор')),
            ],
            options={
                'verbose_name': 'Жанр',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория'},
        ),
    ]
